In [8]:
GRID_H,  GRID_W  = 13 , 13
BATCH_SIZE       = 16

In [5]:
import tensorflow as tf
sess = tf.InteractiveSession()


In [6]:



sess.close()
sess = tf.InteractiveSession()



cell_x = tf.to_float(tf.reshape(tf.tile(tf.range(GRID_W), [GRID_H]), (1, GRID_H, GRID_W, 1, 1)))


print(cell_x.shape)


print("")

a=tf.Print(cell_x,[cell_x],message="cell_x:")
a.eval()




#sess.close()

#print()

(1, 13, 13, 1, 1)



array([[[[[ 0.]],

         [[ 1.]],

         [[ 2.]],

         [[ 3.]],

         [[ 4.]],

         [[ 5.]],

         [[ 6.]],

         [[ 7.]],

         [[ 8.]],

         [[ 9.]],

         [[10.]],

         [[11.]],

         [[12.]]],


        [[[ 0.]],

         [[ 1.]],

         [[ 2.]],

         [[ 3.]],

         [[ 4.]],

         [[ 5.]],

         [[ 6.]],

         [[ 7.]],

         [[ 8.]],

         [[ 9.]],

         [[10.]],

         [[11.]],

         [[12.]]],


        [[[ 0.]],

         [[ 1.]],

         [[ 2.]],

         [[ 3.]],

         [[ 4.]],

         [[ 5.]],

         [[ 6.]],

         [[ 7.]],

         [[ 8.]],

         [[ 9.]],

         [[10.]],

         [[11.]],

         [[12.]]],


        [[[ 0.]],

         [[ 1.]],

         [[ 2.]],

         [[ 3.]],

         [[ 4.]],

         [[ 5.]],

         [[ 6.]],

         [[ 7.]],

         [[ 8.]],

         [[ 9.]],

         [[10.]],

         [[11.]],

         [[12.]]],


    

In [7]:
sess.close()
sess = tf.InteractiveSession()


cell_y = tf.transpose(cell_x, (0,2,1,3,4))
print(cell_y.shape)

b=tf.Print(cell_y,[cell_y],message="cell_y:")
b.eval()

(1, 13, 13, 1, 1)


array([[[[[ 0.]],

         [[ 0.]],

         [[ 0.]],

         [[ 0.]],

         [[ 0.]],

         [[ 0.]],

         [[ 0.]],

         [[ 0.]],

         [[ 0.]],

         [[ 0.]],

         [[ 0.]],

         [[ 0.]],

         [[ 0.]]],


        [[[ 1.]],

         [[ 1.]],

         [[ 1.]],

         [[ 1.]],

         [[ 1.]],

         [[ 1.]],

         [[ 1.]],

         [[ 1.]],

         [[ 1.]],

         [[ 1.]],

         [[ 1.]],

         [[ 1.]],

         [[ 1.]]],


        [[[ 2.]],

         [[ 2.]],

         [[ 2.]],

         [[ 2.]],

         [[ 2.]],

         [[ 2.]],

         [[ 2.]],

         [[ 2.]],

         [[ 2.]],

         [[ 2.]],

         [[ 2.]],

         [[ 2.]],

         [[ 2.]]],


        [[[ 3.]],

         [[ 3.]],

         [[ 3.]],

         [[ 3.]],

         [[ 3.]],

         [[ 3.]],

         [[ 3.]],

         [[ 3.]],

         [[ 3.]],

         [[ 3.]],

         [[ 3.]],

         [[ 3.]],

         [[ 3.]]],


    

In [9]:
sess.close()
sess = tf.InteractiveSession()

cell_grid = tf.tile(tf.concat([cell_x,cell_y], -1), [BATCH_SIZE, 1, 1, 5, 1])

print(cell_grid.shape)

c=tf.Print(cell_grid,[cell_grid],message="cell_grid:")
c.eval()

(16, 13, 13, 5, 2)


array([[[[[ 0.,  0.],
          [ 0.,  0.],
          [ 0.,  0.],
          [ 0.,  0.],
          [ 0.,  0.]],

         [[ 1.,  0.],
          [ 1.,  0.],
          [ 1.,  0.],
          [ 1.,  0.],
          [ 1.,  0.]],

         [[ 2.,  0.],
          [ 2.,  0.],
          [ 2.,  0.],
          [ 2.,  0.],
          [ 2.,  0.]],

         ...,

         [[10.,  0.],
          [10.,  0.],
          [10.,  0.],
          [10.,  0.],
          [10.,  0.]],

         [[11.,  0.],
          [11.,  0.],
          [11.,  0.],
          [11.,  0.],
          [11.,  0.]],

         [[12.,  0.],
          [12.,  0.],
          [12.,  0.],
          [12.,  0.],
          [12.,  0.]]],


        [[[ 0.,  1.],
          [ 0.,  1.],
          [ 0.,  1.],
          [ 0.,  1.],
          [ 0.,  1.]],

         [[ 1.,  1.],
          [ 1.,  1.],
          [ 1.,  1.],
          [ 1.,  1.],
          [ 1.,  1.]],

         [[ 2.,  1.],
          [ 2.,  1.],
          [ 2.,  1.],
          [ 2.,  1.],

In [16]:
strided_slice=cell_x[...,:3]

print()
print(strided_slice.shape)

(1, 13, 13, 1, 1)


In [18]:
print("here")
print("now")
pint("typo")
print("meh")


here
now


NameError: name 'pint' is not defined